- id: s1
  route:
  - from: Siena
    merchandise:
      Bananas: 13
      Butter: 15
      Cheese: 13
      Meat: 23
      Rice: 14
      Tomatoes: 17
    to: Bergamo
  - from: Bergamo
    merchandise:
      Bread: 13
      Potatoes: 6
      Yogurt: 28
    to: Palermo
  - from: Palermo
    merchandise:
      Pasta: 16
      Pens: 21
      Potatoes: 7
      Tomatoes: 3
      Yogurt: 29
    to: Venezia
  - from: Venezia
    merchandise:
      Beer: 16
      Tomatoes: 29
      Yogurt: 24
    to: Trento
  - from: Trento
    merchandise:
      Beer: 25
      Bread: 16
      Chocolate: 12
      Honey: 24
      Tea: 20
      Tomatoes: 16
    to: Bolzano
- id: s2
  route:
  - from: Bolzano
    merchandise:
      Butter: 30
      Honey: 15
      Meat: 6
      Pasta: 13
      Potatoes: 19
    to: Napoli
  - from: Napoli
    merchandise:
      Bread: 23
      Carrots: 17
      Cheese: 14
      Rice: 24
      Tea: 29
    to: Torino
  - from: Torino
    merchandise:
      Butter: 26
      Carrots: 10
      Pasta: 12
      Rice: 21
      Tomatoes: 7
      Yogurt: 3
    to: Padua
  - from: Padua
    merchandise:
      Honey: 11
      Meat: 5
      Tomatoes: 12
    to: Genova
  - from: Genova
    merchandise:
      Apples: 15
      Milk: 11
      Tea: 29
      Tomatoes: 29
    to: Rome
  - from: Rome
    merchandise:
      Bananas: 27
      Beer: 3
      Cheese: 9
      Pasta: 2
      Pens: 18
    to: Palermo
- id: s3
  route:
  - from: Lecce
    merchandise:
      Beer: 30
      Honey: 14
      Meat: 17
      Potatoes: 17
      Yogurt: 17
    to: Modena
  - from: Modena
    merchandise:
      Bananas: 29
      Honey: 20
      Meat: 21
      Tomatoes: 30
    to: Pisa
  - from: Pisa
    merchandise:
      Bananas: 18
      Cheese: 20
      Fish: 8
      Meat: 3
      Pens: 14
      Potatoes: 22
    to: Palermo
  - from: Palermo
    merchandise:
      Bananas: 23
      Butter: 22
      Honey: 30
      Tea: 26
      Water: 15
      Yogurt: 18
    to: Milano
  - from: Milano
    merchandise:
      Cheese: 20
      Chocolate: 2
      Rice: 5
      Yogurt: 6
    to: Napoli
- id: s4
  route:
  - from: Bolzano
    merchandise:
      Bread: 17
      Cheese: 20
      Water: 30
      Yogurt: 27
    to: Pisa
  - from: Pisa
    merchandise:
      Cheese: 7
      Meat: 14
      Potatoes: 23
      Rice: 7
      Tea: 15
    to: Padua
  - from: Padua
    merchandise:
      Bread: 18
      Cheese: 18
      Fish: 21
      Pasta: 14
    to: Trento
  - from: Trento
    merchandise:
      Bananas: 30
      Potatoes: 26
      Tea: 21
    to: Bergamo
  - from: Bergamo
    merchandise:
      Apples: 16
      Milk: 5
      Tea: 13
      Water: 5
    to: Milano
  - from: Milano
    merchandise:
      Apples: 10
      Bread: 13
      Chocolate: 3
      Meat: 6
      Tomatoes: 13
    to: Torino
- id: s5
  route:
  - from: Palermo
    merchandise:
      Butter: 28
      Chocolate: 7
      Meat: 6
      Tea: 9
      Tomatoes: 22
      Water: 9
    to: Bologna
  - from: Bologna
    merchandise:
      Chocolate: 24
      Pasta: 7
      Pens: 3
    to: Verona
  - from: Verona
    merchandise:
      Beer: 27
      Butter: 17
      Chocolate: 26
      Meat: 25
      Potatoes: 16
      Tomatoes: 11
    to: Genova
- id: s6
  route:
  - from: Bolzano
    merchandise:
      Beer: 12
      Cheese: 13
      Honey: 29
      Milk: 29
      Rice: 4
      Water: 15
    to: Napoli
  - from: Napoli
    merchandise:
      Butter: 2
      Chocolate: 29
      Meat: 6
      Water: 19
    to: Padua
  - from: Padua
    merchandise:
      Butter: 15
      Carrots: 6
      Chocolate: 18
      Pasta: 23
      Potatoes: 24
    to: Rome
  - from: Rome
    merchandise:
      Chocolate: 8
      Fish: 5
      Pasta: 17
      Water: 12
    to: Modena
- id: s7
  route:
  - from: Milano
    merchandise:
      Apples: 9
      Beer: 12
      Milk: 29
      Potatoes: 12
      Tea: 6
    to: Bergamo
  - from: Bergamo
    merchandise:
      Apples: 6
      Fish: 28
      Pasta: 12
      Pens: 7
      Tomatoes: 16
    to: Bologna
  - from: Bologna
    merchandise:
      Apples: 14
      Bananas: 22
      Cheese: 19
      Fish: 16
      Honey: 4
    to: Bolzano
  - from: Bolzano
    merchandise:
      Bananas: 26
      Bread: 26
      Butter: 29
      Pens: 9
      Rice: 9
      Tomatoes: 26
    to: Udine
- id: s8
  route:
  - from: Bolzano
    merchandise:
      Butter: 29
      Fish: 10
      Yogurt: 17
    to: Torino
  - from: Torino
    merchandise:
      Meat: 15
      Tomatoes: 4
      Yogurt: 4
    to: Venezia
  - from: Venezia
    merchandise:
      Apples: 3
      Bananas: 29
      Bread: 18
      Carrots: 13
      Meat: 10
      Water: 26
    to: Bologna
  - from: Bologna
    merchandise:
      Apples: 27
      Bananas: 29
      Carrots: 21
      Cheese: 24
      Honey: 9
      Tea: 19
    to: Udine
- id: s9
  route:
  - from: Genova
    merchandise:
      Apples: 29
      Beer: 23
      Bread: 4
      Honey: 4
      Milk: 12
      Pasta: 13
    to: Bologna
  - from: Bologna
    merchandise:
      Cheese: 6
      Milk: 6
      Pasta: 22
      Rice: 23
      Tea: 8
      Tomatoes: 3
    to: Napoli
  - from: Napoli
    merchandise:
      Fish: 26
      Tea: 14
      Yogurt: 19
    to: Bolzano
  - from: Bolzano
    merchandise:
      Cheese: 23
      Milk: 7
      Pasta: 3
    to: Bergamo
  - from: Bergamo
    merchandise:
      Beer: 19
      Meat: 16
      Potatoes: 20
      Rice: 2
    to: Venezia
- id: s10
  route:
  - from: Lecce
    merchandise:
      Chocolate: 4
      Pasta: 29
      Pens: 24
      Tomatoes: 5
    to: Firenze
  - from: Firenze
    merchandise:
      Bananas: 16
      Rice: 29
      Tomatoes: 25
    to: Milano
  - from: Milano
    merchandise:
      Beer: 7
      Milk: 26
      Pasta: 20
      Pens: 28
      Potatoes: 27
      Water: 20
    to: Modena
  - from: Modena
    merchandise:
      Bananas: 2
      Bread: 16
      Cheese: 2
      Chocolate: 19
      Fish: 19
      Honey: 28
    to: Bolzano
  - from: Bolzano
    merchandise:
      Apples: 22
      Beer: 10
      Butter: 29
      Milk: 14
      Pens: 25
      Potatoes: 23
    to: Genova
- id: s11
  route:
  - from: Bergamo
    merchandise:
      Bananas: 25
      Cheese: 19
      Fish: 8
      Pens: 24
    to: Napoli
  - from: Napoli
    merchandise:
      Apples: 25
      Bananas: 20
      Beer: 9
      Bread: 21
      Honey: 21
      Potatoes: 4
    to: Udine
  - from: Udine
    merchandise:
      Beer: 25
      Carrots: 9
      Honey: 16
      Meat: 15
      Tea: 2
      Tomatoes: 3
    to: Venezia
  - from: Venezia
    merchandise:
      Bananas: 3
      Beer: 28
      Fish: 8
      Potatoes: 16
      Tea: 19
    to: Monza
- id: s12
  route:
  - from: Venezia
    merchandise:
      Bread: 6
      Meat: 21
      Milk: 10
      Potatoes: 24
      Rice: 30
    to: Trento
  - from: Trento
    merchandise:
      Cheese: 8
      Water: 26
      Yogurt: 15
    to: Palermo
  - from: Palermo
    merchandise:
      Butter: 2
      Meat: 29
      Pasta: 2
      Potatoes: 14
      Rice: 4
      Water: 8
    to: Siena
- id: s13
  route:
  - from: Verona
    merchandise:
      Cheese: 5
      Chocolate: 21
      Honey: 12
      Rice: 9
    to: Bergamo
  - from: Bergamo
    merchandise:
      Apples: 15
      Beer: 27
      Carrots: 22
      Meat: 3
    to: Modena
  - from: Modena
    merchandise:
      Bananas: 2
      Beer: 26
      Bread: 4
      Honey: 7
      Milk: 4
    to: Rome
- id: s14
  route:
  - from: Milano
    merchandise:
      Chocolate: 11
      Meat: 11
      Potatoes: 9
      Rice: 25
      Tea: 27
      Water: 2
    to: Siena
  - from: Siena
    merchandise:
      Cheese: 16
      Honey: 4
      Water: 29
      Yogurt: 11
    to: Bologna
  - from: Bologna
    merchandise:
      Honey: 19
      Tomatoes: 27
      Water: 6
    to: Monza
  - from: Monza
    merchandise:
      Beer: 11
      Meat: 15
      Rice: 20
    to: Lecce
  - from: Lecce
    merchandise:
      Bananas: 26
      Bread: 15
      Meat: 27
    to: Modena
- id: s15
  route:
  - from: Bolzano
    merchandise:
      Carrots: 28
      Water: 16
      Yogurt: 17
    to: Monza
  - from: Monza
    merchandise:
      Apples: 14
      Bread: 27
      Butter: 15
      Fish: 15
      Meat: 27
      Tomatoes: 20
    to: Rome
  - from: Rome
    merchandise:
      Pens: 14
      Potatoes: 24
      Rice: 17
      Tomatoes: 3
      Yogurt: 8
    to: Torino
  - from: Torino
    merchandise:
      Bananas: 30
      Bread: 10
      Butter: 15
      Cheese: 7
      Potatoes: 21
    to: Palermo
  - from: Palermo
    merchandise:
      Carrots: 16
      Meat: 8
      Pens: 25
      Rice: 16
    to: Padua
- id: s16
  route:
  - from: Milano
    merchandise:
      Beer: 3
      Chocolate: 14
      Fish: 30
      Meat: 5
      Tea: 15
    to: Bolzano
  - from: Bolzano
    merchandise:
      Apples: 22
      Butter: 23
      Carrots: 14
    to: Palermo
  - from: Palermo
    merchandise:
      Apples: 15
      Cheese: 7
      Pasta: 25
      Potatoes: 5
      Tea: 6
      Yogurt: 8
    to: Monza
  - from: Monza
    merchandise:
      Apples: 30
      Chocolate: 7
      Rice: 10
    to: Venezia
  - from: Venezia
    merchandise:
      Chocolate: 16
      Pasta: 12
      Potatoes: 10
    to: Modena
- id: s17
  route:
  - from: Lecce
    merchandise:
      Beer: 22
      Meat: 10
      Pens: 9
      Potatoes: 9
      Tea: 11
    to: Padua
  - from: Padua
    merchandise:
      Meat: 5
      Milk: 29
      Pens: 29
      Tomatoes: 25
    to: Bologna
  - from: Bologna
    merchandise:
      Bread: 23
      Carrots: 24
      Pens: 12
      Tea: 19
      Yogurt: 20
    to: Genova
  - from: Genova
    merchandise:
      Butter: 22
      Fish: 13
      Meat: 27
    to: Torino
  - from: Torino
    merchandise:
      Bread: 16
      Cheese: 7
      Chocolate: 3
      Water: 27
    to: Palermo
  - from: Palermo
    merchandise:
      Bananas: 10
      Beer: 23
      Milk: 25
      Pens: 18
      Rice: 30
      Water: 16
    to: Venezia
- id: s18
  route:
  - from: Palermo
    merchandise:
      Apples: 15
      Chocolate: 3
      Tea: 7
    to: Lecce
  - from: Lecce
    merchandise:
      Carrots: 22
      Honey: 23
      Milk: 2
      Pens: 28
      Potatoes: 6
    to: Bergamo
  - from: Bergamo
    merchandise:
      Pens: 17
      Potatoes: 11
      Tea: 9
      Yogurt: 16
    to: Firenze
- id: s19
  route:
  - from: Milano
    merchandise:
      Beer: 23
      Butter: 14
      Honey: 3
      Meat: 29
      Milk: 19
      Tea: 24
    to: Palermo
  - from: Palermo
    merchandise:
      Butter: 6
      Honey: 10
      Pasta: 23
      Potatoes: 25
      Yogurt: 10
    to: Torino
  - from: Torino
    merchandise:
      Bread: 23
      Honey: 24
      Pens: 27
      Rice: 18
      Tea: 6
      Water: 18
    to: Bolzano
- id: s20
  route:
  - from: Bolzano
    merchandise:
      Butter: 20
      Tomatoes: 18
      Yogurt: 13
    to: Siena
  - from: Siena
    merchandise:
      Carrots: 2
      Honey: 6
      Tea: 20
    to: Bergamo
  - from: Bergamo
    merchandise:
      Bananas: 14
      Fish: 2
      Rice: 8
      Tomatoes: 21
      Yogurt: 23
    to: Udine
