- id: s1
  route:
  - from: Modena
    mercandise:
      Beer: 4
      Butter: 2
      Milk: 19
      Potatoes: 21
      Tomatoes: 29
      Water: 12
    to: Napoli
  - from: Napoli
    mercandise:
      Bananas: 17
      Fish: 21
      Pasta: 7
      Rice: 7
      Tomatoes: 10
    to: Milano
  - from: Milano
    mercandise:
      Carrots: 27
      Honey: 22
      Milk: 15
      Potatoes: 23
      Tea: 21
      Tomatoes: 18
    to: Verona
  - from: Verona
    mercandise:
      Carrots: 7
      Potatoes: 6
      Rice: 15
      Water: 9
      Yogurt: 2
    to: Torino
  - from: Torino
    mercandise:
      Chocolate: 21
      Fish: 22
      Honey: 20
      Yogurt: 28
    to: Bergamo
  - from: Bergamo
    mercandise:
      Cheese: 17
      Tomatoes: 19
      Yogurt: 8
    to: Lecce
- id: s2
  route:
  - from: Napoli
    mercandise:
      Meat: 16
      Milk: 6
      Pasta: 2
      Pens: 13
      Tomatoes: 21
      Water: 7
    to: Modena
  - from: Modena
    mercandise:
      Cheese: 21
      Honey: 21
      Meat: 9
      Water: 11
    to: Venezia
  - from: Venezia
    mercandise:
      Apples: 29
      Carrots: 4
      Chocolate: 9
      Honey: 20
      Milk: 4
      Potatoes: 3
    to: Rome
  - from: Rome
    mercandise:
      Butter: 6
      Milk: 10
      Potatoes: 4
      Rice: 29
      Tomatoes: 19
    to: Pisa
  - from: Pisa
    mercandise:
      Beer: 22
      Bread: 17
      Honey: 12
    to: Milano
- id: s3
  route:
  - from: Rome
    mercandise:
      Bananas: 2
      Bread: 30
      Carrots: 8
      Cheese: 19
      Meat: 28
      Rice: 23
    to: Bolzano
  - from: Bolzano
    mercandise:
      Apples: 29
      Bread: 6
      Fish: 5
      Tea: 30
    to: Lecce
  - from: Lecce
    mercandise:
      Beer: 9
      Bread: 24
      Honey: 5
      Tomatoes: 16
      Water: 3
    to: Modena
  - from: Modena
    mercandise:
      Cheese: 8
      Milk: 23
      Tomatoes: 29
    to: Napoli
  - from: Napoli
    mercandise:
      Bananas: 14
      Beer: 8
      Carrots: 20
      Pens: 6
      Potatoes: 30
      Rice: 24
    to: Trento
  - from: Trento
    mercandise:
      Apples: 22
      Bananas: 3
      Carrots: 23
      Cheese: 4
      Milk: 28
      Potatoes: 28
    to: Torino
- id: s4
  route:
  - from: Trento
    mercandise:
      Bananas: 24
      Cheese: 2
      Chocolate: 27
      Meat: 21
      Tea: 20
    to: Padua
  - from: Padua
    mercandise:
      Bananas: 27
      Bread: 12
      Cheese: 15
      Honey: 2
      Meat: 9
    to: Firenze
  - from: Firenze
    mercandise:
      Beer: 23
      Chocolate: 28
      Meat: 27
      Pasta: 8
      Tomatoes: 29
    to: Modena
  - from: Modena
    mercandise:
      Carrots: 18
      Honey: 7
      Pasta: 24
      Rice: 25
      Tea: 21
      Tomatoes: 18
    to: Napoli
- id: s5
  route:
  - from: Siena
    mercandise:
      Apples: 18
      Beer: 23
      Pasta: 29
    to: Verona
  - from: Verona
    mercandise:
      Chocolate: 23
      Meat: 29
      Tomatoes: 9
      Yogurt: 21
    to: Napoli
  - from: Napoli
    mercandise:
      Apples: 18
      Beer: 23
      Cheese: 15
      Meat: 17
      Pasta: 9
    to: Torino
  - from: Torino
    mercandise:
      Apples: 17
      Bananas: 5
      Meat: 22
      Pens: 13
      Potatoes: 21
    to: Bergamo
  - from: Bergamo
    mercandise:
      Cheese: 23
      Pasta: 7
      Water: 22
    to: Rome
- id: s6
  route:
  - from: Udine
    mercandise:
      Cheese: 14
      Chocolate: 9
      Water: 18
    to: Torino
  - from: Torino
    mercandise:
      Butter: 19
      Fish: 24
      Potatoes: 27
      Tomatoes: 4
      Yogurt: 30
    to: Lecce
  - from: Lecce
    mercandise:
      Carrots: 3
      Chocolate: 9
      Potatoes: 9
    to: Trento
- id: s7
  route:
  - from: Lecce
    mercandise:
      Apples: 2
      Butter: 4
      Tea: 14
      Water: 8
    to: Genova
  - from: Genova
    mercandise:
      Butter: 2
      Cheese: 8
      Chocolate: 15
    to: Padua
  - from: Padua
    mercandise:
      Apples: 8
      Bananas: 22
      Butter: 30
      Cheese: 17
      Chocolate: 2
      Pens: 9
    to: Napoli
- id: s8
  route:
  - from: Padua
    mercandise:
      Butter: 21
      Fish: 10
      Honey: 14
    to: Bolzano
  - from: Bolzano
    mercandise:
      Beer: 26
      Honey: 30
      Milk: 13
      Tomatoes: 28
      Water: 4
      Yogurt: 12
    to: Udine
  - from: Udine
    mercandise:
      Honey: 2
      Pasta: 5
      Potatoes: 24
      Water: 28
    to: Bergamo
  - from: Bergamo
    mercandise:
      Apples: 13
      Bread: 27
      Meat: 30
      Pasta: 16
    to: Rome
- id: s9
  route:
  - from: Udine
    mercandise:
      Beer: 2
      Carrots: 20
      Fish: 18
      Meat: 13
    to: Siena
  - from: Siena
    mercandise:
      Meat: 6
      Pasta: 8
      Pens: 29
      Rice: 26
    to: Rome
  - from: Rome
    mercandise:
      Chocolate: 14
      Pasta: 6
      Tomatoes: 27
      Water: 7
    to: Bologna
  - from: Bologna
    mercandise:
      Bread: 26
      Carrots: 15
      Fish: 25
      Meat: 11
      Yogurt: 8
    to: Verona
  - from: Verona
    mercandise:
      Bread: 4
      Cheese: 17
      Fish: 21
      Honey: 6
      Pasta: 7
      Pens: 2
    to: Genova
- id: s10
  route:
  - from: Bologna
    mercandise:
      Honey: 4
      Meat: 8
      Milk: 22
      Pasta: 28
      Pens: 26
      Water: 18
    to: Trento
  - from: Trento
    mercandise:
      Milk: 20
      Rice: 3
      Water: 27
      Yogurt: 3
    to: Torino
  - from: Torino
    mercandise:
      Meat: 9
      Milk: 4
      Rice: 12
    to: Bergamo
  - from: Bergamo
    mercandise:
      Apples: 14
      Beer: 24
      Cheese: 3
      Chocolate: 29
      Potatoes: 7
      Tomatoes: 15
    to: Modena
  - from: Modena
    mercandise:
      Bananas: 5
      Cheese: 9
      Fish: 22
      Milk: 6
    to: Siena
  - from: Siena
    mercandise:
      Apples: 28
      Fish: 23
      Meat: 22
      Pasta: 3
      Pens: 21
      Tea: 4
    to: Verona
- id: s11
  route:
  - from: Bergamo
    mercandise:
      Beer: 13
      Carrots: 28
      Fish: 29
      Pens: 5
      Water: 17
    to: Lecce
  - from: Lecce
    mercandise:
      Apples: 10
      Bananas: 5
      Milk: 9
    to: Padua
  - from: Padua
    mercandise:
      Bananas: 4
      Beer: 9
      Butter: 27
      Cheese: 14
      Tomatoes: 9
    to: Modena
- id: s12
  route:
  - from: Rome
    mercandise:
      Bananas: 21
      Butter: 22
      Fish: 15
      Meat: 19
      Tea: 17
    to: Lecce
  - from: Lecce
    mercandise:
      Bread: 18
      Carrots: 11
      Fish: 2
      Rice: 5
      Tea: 29
      Tomatoes: 10
    to: Verona
  - from: Verona
    mercandise:
      Beer: 26
      Bread: 19
      Carrots: 24
      Pasta: 25
      Pens: 21
      Water: 11
    to: Siena
  - from: Siena
    mercandise:
      Carrots: 3
      Cheese: 19
      Pasta: 24
      Tomatoes: 28
      Water: 15
    to: Bologna
- id: s13
  route:
  - from: Bergamo
    mercandise:
      Bananas: 13
      Beer: 2
      Carrots: 14
      Cheese: 30
      Chocolate: 11
    to: Bologna
  - from: Bologna
    mercandise:
      Beer: 12
      Chocolate: 2
      Meat: 3
      Pens: 10
      Tomatoes: 2
    to: Torino
  - from: Torino
    mercandise:
      Apples: 22
      Bread: 8
      Carrots: 20
      Cheese: 12
      Chocolate: 18
      Tomatoes: 9
    to: Genova
  - from: Genova
    mercandise:
      Bread: 3
      Meat: 22
      Pens: 8
      Potatoes: 6
      Rice: 23
    to: Padua
  - from: Padua
    mercandise:
      Bread: 7
      Carrots: 23
      Fish: 13
      Water: 9
    to: Rome
- id: s14
  route:
  - from: Trento
    mercandise:
      Cheese: 27
      Fish: 22
      Honey: 27
      Tomatoes: 16
    to: Siena
  - from: Siena
    mercandise:
      Honey: 30
      Meat: 17
      Pasta: 27
      Potatoes: 22
      Water: 28
      Yogurt: 6
    to: Rome
  - from: Rome
    mercandise:
      Bread: 27
      Honey: 4
      Meat: 19
      Rice: 3
    to: Verona
  - from: Verona
    mercandise:
      Butter: 23
      Cheese: 8
      Meat: 2
      Potatoes: 8
      Tomatoes: 18
      Water: 19
    to: Udine
  - from: Udine
    mercandise:
      Carrots: 12
      Honey: 25
      Rice: 14
      Tomatoes: 10
    to: Padua
  - from: Padua
    mercandise:
      Beer: 13
      Cheese: 30
      Milk: 3
      Yogurt: 14
    to: Palermo
- id: s15
  route:
  - from: Milano
    mercandise:
      Bread: 5
      Carrots: 11
      Cheese: 16
      Fish: 13
      Tomatoes: 23
    to: Trento
  - from: Trento
    mercandise:
      Apples: 18
      Bread: 8
      Butter: 8
      Cheese: 30
      Potatoes: 17
    to: Venezia
  - from: Venezia
    mercandise:
      Apples: 18
      Bananas: 15
      Fish: 5
      Meat: 27
      Rice: 4
      Water: 12
    to: Bolzano
- id: s16
  route:
  - from: Napoli
    mercandise:
      Meat: 20
      Pasta: 17
      Water: 15
    to: Rome
  - from: Rome
    mercandise:
      Carrots: 15
      Chocolate: 8
      Honey: 21
      Milk: 5
      Rice: 6
      Tea: 23
    to: Milano
  - from: Milano
    mercandise:
      Honey: 11
      Milk: 18
      Pasta: 10
      Potatoes: 8
      Tomatoes: 25
    to: Udine
- id: s17
  route:
  - from: Genova
    mercandise:
      Beer: 19
      Chocolate: 6
      Fish: 13
      Honey: 4
      Meat: 13
      Potatoes: 7
    to: Padua
  - from: Padua
    mercandise:
      Carrots: 6
      Cheese: 29
      Fish: 14
    to: Napoli
  - from: Napoli
    mercandise:
      Bananas: 23
      Butter: 3
      Chocolate: 3
      Potatoes: 18
    to: Modena
  - from: Modena
    mercandise:
      Beer: 28
      Bread: 27
      Butter: 22
      Fish: 19
      Potatoes: 30
      Tea: 24
    to: Pisa
  - from: Pisa
    mercandise:
      Butter: 21
      Cheese: 16
      Chocolate: 26
    to: Lecce
- id: s18
  route:
  - from: Palermo
    mercandise:
      Beer: 22
      Cheese: 11
      Chocolate: 12
      Fish: 29
      Tomatoes: 9
    to: Firenze
  - from: Firenze
    mercandise:
      Bananas: 17
      Chocolate: 26
      Honey: 15
      Tomatoes: 21
    to: Monza
  - from: Monza
    mercandise:
      Apples: 13
      Bread: 10
      Pasta: 22
      Pens: 22
      Tea: 7
    to: Bergamo
  - from: Bergamo
    mercandise:
      Beer: 18
      Potatoes: 17
      Tomatoes: 11
      Water: 13
    to: Udine
  - from: Udine
    mercandise:
      Carrots: 18
      Meat: 29
      Pens: 16
      Tea: 29
    to: Torino
- id: s19
  route:
  - from: Lecce
    mercandise:
      Apples: 23
      Milk: 9
      Pasta: 3
      Potatoes: 8
    to: Bologna
  - from: Bologna
    mercandise:
      Bananas: 21
      Chocolate: 10
      Meat: 22
      Pens: 7
      Potatoes: 22
      Tea: 4
    to: Modena
  - from: Modena
    mercandise:
      Carrots: 21
      Honey: 7
      Meat: 11
      Water: 23
      Yogurt: 6
    to: Genova
  - from: Genova
    mercandise:
      Apples: 18
      Chocolate: 18
      Pens: 6
      Tea: 14
      Water: 28
      Yogurt: 5
    to: Siena
  - from: Siena
    mercandise:
      Cheese: 5
      Meat: 17
      Tomatoes: 26
    to: Pisa
- id: s20
  route:
  - from: Palermo
    mercandise:
      Carrots: 27
      Cheese: 27
      Honey: 13
      Milk: 16
    to: Bergamo
  - from: Bergamo
    mercandise:
      Bananas: 14
      Carrots: 25
      Cheese: 3
      Fish: 27
      Rice: 9
      Water: 8
    to: Monza
  - from: Monza
    mercandise:
      Apples: 26
      Butter: 26
      Milk: 24
      Pens: 28
      Potatoes: 14
    to: Firenze
  - from: Firenze
    mercandise:
      Apples: 12
      Carrots: 2
      Chocolate: 20
      Honey: 27
      Rice: 26
    to: Genova
